### ISSUE TITLE
Registration requires authentication

### ISSUE THREAD

**Issue by minhducsun2002** [vnma0/wafter#113]
`src/routes/users.js`
```
router.use(auth);

/**
 * GET /users
 * If user -> redirect to user
 */
router.get("/", (req, res) => {
    res.redirect(req.baseUrl + "/" + req.user._id);
});

router.post("/", bruteForce, async (req, res) => {
```

The `auth` middleware will kick in first, preventing registrations to work properly.

**Comment by minhducsun2002** [comment]
Also, moving the POST handler up, before the `router.use(auth)`,  seems to resolve the problem. However, it errors out :
```
(node:16167) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isAdmin' of undefined
    at <redacted>/wafter/src/routes/users.js:22:33
    at Layer.handle [as handle_request] (<redacted>/wafter/node_modules/express/lib/router/layer.js:95:5)
    at next (<redacted>/wafter/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (<redacted>/wafter/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (<redacted>/wafter/node_modules/express/lib/router/layer.js:95:5)
    at <redacted>/wafter/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (<redacted>/wafter/node_modules/express/lib/router/index.js:335:12)
    at next (<redacted>/wafter/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (<redacted>/wafter/node_modules/express/lib/router/index.js:174:3)
    at router (<redacted>/wafter/node_modules/express/lib/router/index.js:47:12)
(node:16167) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16167) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Looks like you are accessing `req.user`, however it is `undefined` since the registration request is not authenticated.

**Comment by dungwinux** [comment]
Because there's a parameter checking if user is Admin. I'll try optional chaining.

**Comment by dungwinux** [comment]
@minhducsun2002, test `fix-113` and see if it works

**Comment by minhducsun2002** [comment]
Yes, it worked. Thank you.
