### ISSUE TITLE
Crash upon occupied port

### ISSUE THREAD

**Issue by minhducsun2002** [vnma0/wafter#69]
On Linux systems : 
(`tty1`)
```
$ nc -nvlp 3001
Listening on [0.0.0.0] (family 2, port 3001)
```

(`tty2`)
```
$ NODE_ENV=production node src/index.js
MIRAI Wafter 1.5
Copyright (c) 2018 Vườn ươm A0. MIT License.
✔ How can I help you ? · Start server
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (net.js:1277:14)
    at listenInCluster (net.js:1325:12)
    at Server.listen (net.js:1412:7)
    at Function.listen (/home/cipher/Projects/wafter/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/cipher/Projects/wafter/src/server.js:72:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1304:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by dungwinux** [comment]
Yes, this issue is already on the case, so please look forward to the fix
