### ISSUE TITLE
Unsynchronizedness and/or data interception triggers unhandled Promise rejection

### ISSUE THREAD

**Issue by minhducsun2002** [vnma0/wafter#70]
```
(node:26924) UnhandledPromiseRejectionWarning: Error: Invalid user_id: T9JhkqPpaNmJSJuX
    at /home/cipher/Projects/wafter/src/data/database.js:120:44
    at newArguments.(anonymous function) (/home/cipher/Projects/wafter/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/home/cipher/Projects/wafter/node_modules/nedb/lib/datastore.js:520:14)
    at callback (/home/cipher/Projects/wafter/node_modules/nedb/lib/cursor.js:126:19)
    at /home/cipher/Projects/wafter/node_modules/nedb/lib/cursor.js:193:12
    at /home/cipher/Projects/wafter/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/home/cipher/Projects/wafter/node_modules/async/lib/async.js:130:20)
    at /home/cipher/Projects/wafter/node_modules/nedb/lib/datastore.js:323:11
    at fn (/home/cipher/Projects/wafter/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/home/cipher/Projects/wafter/node_modules/async/lib/async.js:498:34)
(node:26924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26924) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:26924) UnhandledPromiseRejectionWarning: Error: Invalid user_id: T9JhkqPpaNmJSJuX
    at /home/cipher/Projects/wafter/src/data/database.js:120:44
    at newArguments.(anonymous function) (/home/cipher/Projects/wafter/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/home/cipher/Projects/wafter/node_modules/nedb/lib/datastore.js:520:14)
    at callback (/home/cipher/Projects/wafter/node_modules/nedb/lib/cursor.js:126:19)
    at /home/cipher/Projects/wafter/node_modules/nedb/lib/cursor.js:193:12
    at /home/cipher/Projects/wafter/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/home/cipher/Projects/wafter/node_modules/async/lib/async.js:130:20)
    at /home/cipher/Projects/wafter/node_modules/nedb/lib/datastore.js:323:11
    at fn (/home/cipher/Projects/wafter/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/home/cipher/Projects/wafter/node_modules/async/lib/async.js:498:34)
(node:26924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by dungwinux** [comment]
Please state your version

**Comment by minhducsun2002** [comment]
[Current](https://github.com/vnma0/wafter/commit/18178720110227cd75eec9b76e3a9ca9fc59063a) [`master`](https://github.com/vnma0/wafter/tree/master) at the time I write this.
```
$ git show HEAD
commit 18178720110227cd75eec9b76e3a9ca9fc59063a (HEAD -> master, tag: v1.7, origin/master, origin/HEAD)
Merge: 28c4467 a33ef07
Author: Nguyễn Tuấn Dũng <ntddebugger@gmail.com>
Date:   Sat Mar 9 18:51:01 2019 +0700

    Merge pull request #58 from vnma0/src-code
    
    Add feature to read submission's source

```

**Comment by dungwinux** [comment]
@minhducsun2002, see #71 (f41544b) if problem still persists
